---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base

patchesStrategicMerge:
  - overlays/development/airsonic-advanced-deployment.yaml
  - overlays/development/airsonic-advanced-pv.yaml
  - overlays/development/airsonic-advanced-service.yaml

namespace: airsonic-advanced
