---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - common.yaml
  - crds.yaml
  - operator.yaml
  - cluster.yaml
  - toolbox.yaml
  - filesystem.yaml
  - dashboard-loadbalancer.yaml

namespace: rook-ceph
