---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mariadb-deployment.yaml
  - mariadb-pvc.yaml
  - nextcloud-configmap.yaml
  - nextcloud-config.yaml
  - nextcloud-deployment.yaml
  - nextcloud-pvc.yaml

namespace: nextcloud
