apiVersion: v1
kind: Service
metadata:
  name: nextcloud-mariadb-svc
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: nextcloud-mariadb
    #app.kubernetes.io/version: "10.8.3"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: nextcloud
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: nextcloud-mariadb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: nextcloud
  ports:
    - port: 3306
      targetPort: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud-mariadb
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: nextcloud-mariadb
    #app.kubernetes.io/version: "10.8.3"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: nextcloud
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  serviceName: mariadb
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/instance: nextcloud-mariadb
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: nextcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/instance: nextcloud-mariadb
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: nextcloud
        app.kubernetes.io/managed-by: argocd
    spec:
      containers:
        - image: mariadb:10.8.3
          name: nextcloud-mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb-secret
                  key: root_password
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-mariadb-config
                  key: database
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb-secret
                  key: username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb-secret
                  key: password
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: nextcloud-mariadb-volume
          ports:
            - containerPort: 3306
              name: mariadb
      volumes:
        - name: nextcloud-mariadb-volume
          persistentVolumeClaim:
            claimName: nextcloud-mariadb-pvc
