apiVersion: v1
kind: Service
metadata:
  name: nextcloud-svc
  labels:
    app.kubernetes.io/name: nginx-fpm
    app.kubernetes.io/instance: nextcloud
    #app.kubernetes.io/version: "24.0.1"
    app.kubernetes.io/component: nginx-fpm
    app.kubernetes.io/part-of: nextcloud
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app.kubernetes.io/name: nginx-fpm
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/component: nginx-fpm
    app.kubernetes.io/part-of: nextcloud
  ports:
    - port: 80
      targetPort: nginx-http
      protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nginx-fpm
    app.kubernetes.io/instance: nextcloud
    #app.kubernetes.io/version: "24.0.1"
    app.kubernetes.io/component: nginx-fpm
    app.kubernetes.io/part-of: nextcloud
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-fpm
      app.kubernetes.io/instance: nextcloud
      app.kubernetes.io/component: nginx-fpm
      app.kubernetes.io/part-of: nextcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-fpm
        app.kubernetes.io/instance: nextcloud
        app.kubernetes.io/component: nginx-fpm
        app.kubernetes.io/part-of: nextcloud
        app.kubernetes.io/managed-by: argocd
    spec:
      containers:
        - image: nginx:1.21-alpine
          name: nextcloud-nginx
          ports:
            - containerPort: 80
              name: nginx-http
              protocol: TCP
          volumeMounts:
            - name: nextcloud-nginx-php-fpm
              mountPath: /etc/nginx/conf.d/
            - mountPath: "/var/www/html"
              name: nextcloud-volume
              readOnly: true
            - mountPath: "/var/www/html/custom_apps"
              name: nextcloud-apps-volume
              readOnly: true
        - image: nextcloud:24.0.1-fpm-alpine
          name: nextcloud-fpm
          env:
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: admin_username
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: admin_password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: trusted_domains
            - name: NEXTCLOUD_UPDATE
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: update
            - name: PHP_MEMORY_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: php_memory_limit
            - name: PHP_UPLOAD_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: php_upload_limit
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-mariadb-config
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb-secret
                  key: password
            - name: MYSQL_HOST
              value: nextcloud-mariadb-svc
            - name: REDIS_HOST
              value: nextcloud-redis-svc
            - name: REDIS_HOST_PORT
              value: "6379"
            - name: REDIS_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-redis-secret
                  key: password
          volumeMounts:
            - mountPath: "/var/www/html"
              name: nextcloud-volume
            - mountPath: "/var/www/html/data"
              name: nextcloud-data-volume
            - mountPath: "/var/www/html/custom_apps"
              name: nextcloud-apps-volume
          ports:
            - containerPort: 9000
              name: fpm
              protocol: TCP
      volumes:
        - name: nextcloud-volume
          persistentVolumeClaim:
            claimName: nextcloud-pvc
        - name: nextcloud-data-volume
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
        - name: nextcloud-apps-volume
          persistentVolumeClaim:
            claimName: nextcloud-apps-pvc
        - name: nextcloud-nginx-php-fpm
          configMap:
            name: nextcloud-config
            items:
              - key: php_fpm_conf
                path: php-fpm.conf
                mode: 0440
