apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
data:
  trusted_domains: ""
  update: "0"
  php_memory_limit: "512M"
  php_upload_limit: "512M"
  php_fpm_conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        location / {
            index index.html index.htm index.php;
        }
    
        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            #fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
            fastcgi_index index.php;
            include fastcgi.conf;
        }
    }
