apiVersion: v1
kind: PersistentVolume
metadata:
  name: airsonic-advanced
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
  labels:
    name: airsonic-pv-music
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.0.32
    path: "/srv/dev-disk-by-id-md-name-openmediavault-volume1/Public/Music/"
  mountOptions:
    - nfsvers=4.2

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airsonic-pvc-music
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: "airsonic-pv-music"

