---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airsonic
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: airsonic
      tier: backend
  template:
    metadata:
      labels:
        app: airsonic
        tier: backend
    spec:
      containers:
        - image: postgres:latest
          name: airsonic-advanced-pgsql
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: airsonic-pgsql
          ports:
            - containerPort: 5432
      volumes:
        - name: airsonic-pgsql
          persistentVolumeClaim:
            claimName: airsonic-pvc-pgsql
