---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airsonic-pv-music
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
  labels:
    name: airsonic-pv-music
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.0.32
    path: "/Music"
  mountOptions:
    - nfsvers=4.2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airsonic-pvc-music
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: "airsonic-pv-music"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airsonic-pv-video
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
  labels:
    name: airsonic-pv-video
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.0.32
    path: "/Video"
  mountOptions:
    - nfsvers=4.2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airsonic-pvc-video
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: "airsonic-pv-video"

