---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airsonic
spec:
  selector:
    matchLabels:
      name: airsonic
  template:
    spec:
      containers:
        - name: airsonic-advanced
          volumeMounts:
            - mountPath: "/var/music"
              name: airsonic-music
      volumes:
        - name: airsonic-music
          persistentVolumeClaim:
            claimName: airsonic-pvc-music

