---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airsonic
spec:
  template:
    spec:
      containers:
        - name: airsonic-advanced
          args:
            - '--spring.datasource.driver-class-name=org.postgresql.Driver'
            - '--spring.datasource.url=jdbc:postgresql://pgsql-svc:5432/airsonic?stringtype=unspecified&raiseExceptionOnSilentRollback=false'

          env:
            - name: spring_datasource_driver_class_name
              value: 'org.postgresql.Driver'
            - name: spring_datasource_url
              value: 'jdbc:postgresql://pgsql-svc:5432/airsonic?stringtype=unspecified&raiseExceptionOnSilentRollback=false'
            - name: spring_datasource_username
              value: postgres
            - name: spring_datasource_password
              value: postgres
            - name: spring_liquibase_parameters_userTableQuote
              value: '"'
          volumeMounts:
            - mountPath: "/var/music"
              name: airsonic-music
            - mountPath: "/var/video"
              name: airsonic-video
            - mountPath: "/var/airsonic"
              name: airsonic-airsonic
            - mountPath: "/var/playlists"
              name: airsonic-playlists
            - mountPath: "/var/podcasts"
              name: airsonic-podcasts
      volumes:
        - name: airsonic-music
          persistentVolumeClaim:
            claimName: airsonic-pvc-music
        - name: airsonic-video
          persistentVolumeClaim:
            claimName: airsonic-pvc-video
        - name: airsonic-airsonic
          persistentVolumeClaim:
            claimName: airsonic-pvc-airsonic
        - name: airsonic-playlists
          persistentVolumeClaim:
            claimName: airsonic-pvc-playlists
        - name: airsonic-podcasts
          persistentVolumeClaim:
            claimName: airsonic-pvc-podcasts
