---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - airsonic-advanced-pv.yaml

patchesStrategicMerge:
  - airsonic-advanced-deployment.yaml
  - airsonic-advanced-service.yaml
