---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airsonic
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: airsonic
  template:
    metadata:
      labels:
        app: airsonic
    spec:
      containers:
        - image: airsonicadvanced/airsonic-advanced:10.6.0
          name: airsonic-advanced
          ports:
            - containerPort: 4040
              name: http-airsonic
              protocol: TCP
            - containerPort: 4041
              name: upnp-airsonic
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: JAVA_OPTS
              value: -Dserver.forward-headers-strategy=native
            - name: AIRSONIC_PORT
              value: "4040"
            - name: UPNP_PORT
              value: "4041"
