---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - netbox-configmap.yaml
  - netbox-deployment.yaml
  - pgsql-configmap.yaml
  - pgsql-statefulset.yaml
  - pgsql-pvc.yaml
  - redis-deployment.yaml

namespace: netbox
