apiVersion: v1
kind: Service
metadata:
  name: netbox-svc
  labels:
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: netbox
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: netbox
  ports:
    - port: 8080
      targetPort: netbox
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
  labels:
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: netbox
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: netbox
      app.kubernetes.io/instance: netbox
      app.kubernetes.io/component: app
      app.kubernetes.io/part-of: netbox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: netbox
        app.kubernetes.io/instance: netbox
        app.kubernetes.io/component: app
        app.kubernetes.io/part-of: netbox
        app.kubernetes.io/managed-by: argocd
    spec:
      containers:
        - image: netboxcommunity/netbox:v3.2.4
          name: netbox
          ports:
            - containerPort: 8080
              name: netbox
              protocol: TCP
          env:
            - name: SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netbox-secret
                  key: superuser_password
            - name: SUPERUSER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: netbox-secret
                  key: superuser_api_token
            - name: DB_HOST
              value: netbox-pgsql-svc
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: netbox-pgsql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netbox-pgsql-secret
                  key: password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: netbox-secret
                  key: secret_key
            - name: REDIS_HOST
              value: netbox-redis-svc
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netbox-redis-secret
                  key: password
            - name: REDIS_CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netbox-redis-secret
                  key: password
            - name: BANNER_TOP
              valueFrom:
                configMapKeyRef:
                  name: netbox-config
                  key: banner_top
            - name: BANNER_BOTTOM
              valueFrom:
                configMapKeyRef:
                  name: netbox-config
                  key: banner_bottom
            - name: BANNER_LOGIN
              valueFrom:
                configMapKeyRef:
                  name: netbox-config
                  key: banner_login
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: netbox-config
                  key: debug
            - name: LOGIN_REQUIRED
              valueFrom:
                configMapKeyRef:
                  name: netbox-config
                  key: login_required
            - name: LOGIN_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: netbox-config
                  key: login_timeout
            - name: TIME_ZONE
              valueFrom:
                configMapKeyRef:
                  name: netbox-config
                  key: time_zone
