apiVersion: v1
kind: Service
metadata:
  name: netbox-pgsql-svc
  labels:
    app.kubernetes.io/name: pgsql
    app.kubernetes.io/instance: netbox-pgsql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: netbox
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app.kubernetes.io/name: pgsql
    app.kubernetes.io/instance: netbox-pgsql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: netbox
  ports:
    - port: 5432
      targetPort: pgsql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: netbox-pgsql
  labels:
    app.kubernetes.io/name: pgsql
    app.kubernetes.io/instance: netbox-pgsql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: netbox
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  serviceName: pgsql
  selector:
    matchLabels:
      app.kubernetes.io/name: pgsql
      app.kubernetes.io/instance: netbox-pgsql
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: netbox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgsql
        app.kubernetes.io/instance: netbox-pgsql
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: netbox
        app.kubernetes.io/managed-by: argocd
    spec:
      containers:
        - image: postgres:14.3-alpine
          name: netbox-pgsql
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: netbox-pgsql-config
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: netbox-pgsql-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netbox-pgsql-secret
                  key: password
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: netbox-pgsql-volume
          ports:
            - containerPort: 5432
              name: pgsql
              protocol: TCP
      volumes:
        - name: netbox-pgsql-volume
          persistentVolumeClaim:
            claimName: netbox-pgsql-pvc
