apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebridge-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      containers:
        - image: oznu/homebridge:2022-02-09
          name: homebridge
          ports:
            - containerPort: 8581
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: PGID
              value: 1000
            - name: PUID
              value: 1000
            - name: HOMEBRIDGE_CONFIG_UI
              value: 1
            - name: HOMEBRIDGE_CONFIG_UI_PORT
              value: 8581


