apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/argocd-service.yaml
# additional resources like ingress rules, cluster and repository secrets.
#resources:
#  - clusters-secrets.yaml
#  - repos-secrets.yaml

# changes to config maps
patchesStrategicMerge:
  - overlays/development/argocd-svc.yaml
